### ISSUE TITLE
Filter by Wildcard / Regex

### ISSUE THREAD

**Issue by RichardHeelin** [nickpeirson/gearman_gtop#2]
There are times when I want to filter by a wildcard / regex, currently attempting to filter by either returns the following error:

```
$ gearman_gtop -sort=2 '-filterInclude=ekm.+Order' '-filterExclude=fail,stale'
panic: runtime error: index out of range

goroutine 16 [running]:
runtime.panic(0x5888a0, 0x6a333c)
    /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
main.drawStatus(0x6a6f98, 0x0, 0x0, 0x8, 0x6, 0x7, 0x7, 0x0, 0x29, 0xa5)
    /Users/nickpeirson/go/src/github.com/nickpeirson/gearman_gtop/gearman_gtop.go:266 +0x4da
main.redraw(0x6a6f98, 0x0, 0x0, 0x8, 0x6, 0x7, 0x7, 0x0)
    /Users/nickpeirson/go/src/github.com/nickpeirson/gearman_gtop/gearman_gtop.go:410 +0x5c
main.main()
    /Users/nickpeirson/go/src/github.com/nickpeirson/gearman_gtop/gearman_gtop.go:443 +0x36b

goroutine 19 [finalizer wait]:
runtime.park(0x417d00, 0x6a6ad0, 0x6a55e9)
    /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x6a6ad0, 0x6a55e9)
    /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
    /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
    /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 20 [runnable]:
os/signal.loop()
    /usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
    /usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 21 [runnable]:
github.com/nsf/termbox-go.func·001()
    /Users/nickpeirson/go/src/github.com/nsf/termbox-go/api.go:87 +0x41a
created by github.com/nsf/termbox-go.Init
    /Users/nickpeirson/go/src/github.com/nsf/termbox-go/api.go:106 +0x82e

goroutine 22 [sleep]:
time.Sleep(0x3b920b49)
    /usr/local/go/src/pkg/runtime/time.goc:39 +0x31
main.getStatus(0xc208004360)
    /Users/nickpeirson/go/src/github.com/nickpeirson/gearman_gtop/gearman_gtop.go:189 +0x64f
created by main.main
    /Users/nickpeirson/go/src/github.com/nickpeirson/gearman_gtop/gearman_gtop.go:437 +0x1d0

goroutine 23 [select]:
github.com/nsf/termbox-go.PollEvent(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/nickpeirson/go/src/github.com/nsf/termbox-go/api.go:245 +0x396
main.handleEvents(0xc20802a8c0, 0xc208004480, 0xc2080043c0, 0xc208004420)
    /Users/nickpeirson/go/src/github.com/nickpeirson/gearman_gtop/gearman_gtop.go:307 +0x29
created by main.main
    /Users/nickpeirson/go/src/github.com/nickpeirson/gearman_gtop/gearman_gtop.go:438 +0x20f
```

**Comment by nickpeirson** [comment]
Release [0.5.0](https://github.com/nickpeirson/gearman_gtop/releases/tag/0.5.0) adds support for regex filtering
